### ISSUE TITLE
CppAPI.hx error causes game to not build on Linux

### ISSUE THREAD

**Issue by GenesisGreen** [lunarcleint/Wednesdays-Infidelity#11]
### Describe your bug here.

When I try compiling the game on Linux, the terminal outputs the errors shown in the Command Prompt/Terminal logs.

### Command Prompt/Terminal logs (if existing)

```bash
source/data/CppAPI.hx:13: characters 15-33 : Class<data.WindowsData> has no field setWindowColorMode
source/data/CppAPI.hx:13: characters 34-38 : Unknown identifier : DARK
source/data/CppAPI.hx:18: characters 15-33 : Class<data.WindowsData> has no field setWindowColorMode
source/data/CppAPI.hx:18: characters 34-39 : Unknown identifier : LIGHT
source/data/CppAPI.hx:23: characters 15-29 : Class<data.WindowsData> has no field setWindowAlpha
source/data/CppAPI.hx:28: characters 15-32 : Class<data.WindowsData> has no field _setWindowLayered
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited the Project.xml file to add the "<define name="PRIVATE_BUILD"/> " tag

**Comment by REALHaydenGaming** [comment]
Same, lunar could you PLEASE add a #if linux tag on the cpp thingy?

Cuz yeah, broken af.

**Comment by lunarcleint** [comment]
Please refer to this issue:
[https://github.com/lunarcleint/Wednesdays-Infidelity/issues/13](url)

**Comment by lunarcleint** [comment]
(If the link doesn't work go the closed issue named `Issue relating to Linux computer's`)

**Comment by REALHaydenGaming** [comment]
> (If the link doesn't work go the closed issue named `Issue relating to Linux computer's`)

Actually, just get rid of the CPP API, as that is windows only (Also get rid of entering in the Spec Detector thingy).
Including WindowData.hx

And just try to find a fix for the hxCodec.

**Comment by lunarcleint** [comment]
Its only there cause if you access it directly throught WindowsData.hx it make cpp compiling errors

**Comment by REALHaydenGaming** [comment]
> Its only there cause if you access it directly throught WindowsData.hx it make cpp compiling errors

Nope. If you completely remove all 3 + removing the access to Specs Dectector.
The mod would run perfectly fine.
