### ISSUE TITLE
Ur mod is too good

### ISSUE THREAD

**Issue by DabbinDude316B** [lunarcleint/Wednesdays-Infidelity#12]
### Describe your bug here.

The mod is 6/5 man

### Command Prompt/Terminal logs (if existing)

```bash
A
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by lunarcleint** [comment]
ong ong
