### ISSUE TITLE
Issue relating to Linux computer's.

### ISSUE THREAD

**Issue by REALHaydenGaming** [lunarcleint/Wednesdays-Infidelity#13]
## Issue 1.
Apparently. When you enable:

Intensive Shader's.
Shader's.
Don't show warning screen.

It make's the entire mod unplayable & cause's the mod to BE crashed EVERY single time.

SS for proof.
![shader issue](https://user-images.githubusercontent.com/107285739/190876015-4dfe6385-9704-4a13-8f28-5e183730092c.png)

Don't fucking make a joke/telling me to get myself a better PC.
Chrome OS is the only PC I will be using for my time.

## Issue 2

When lime testing linux.
I got this error at the very END.

![Screenshot 2022-09-17 9 34 37 PM](https://user-images.githubusercontent.com/107285739/190884261-10c021eb-1fe7-4643-9923-3c4a80ae5e7e.png)

### Command Prompt/Terminal logs (if existing)

Issue 1:
_None existing_

Issue 2:

/usr/bin/ld:/home/hayden/haxelib/hxCodec/2,5,1/lib/vlc/lib/Linux/libvlccore.so.9: file format not recognized; treating as linker script
/usr/bin/ld:/home/hayden/haxelib/hxCodec/2,5,1/lib/vlc/lib/Linux/libvlccore.so.9:0: syntax error
collect2: error: ld returned 1 exit status

### Are you modding a build from source or with Lua?

Issue 1:
None

Issue 2:
Source
### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

For issue 1.
no lol, it's literally the Patch, build.

For issue 2
Added some thing's for a build.

**Comment by lunarcleint** [comment]
Hello, thanks for the concern, but I never intended on making a linux build. This is for many reasons, but mostly because like 99% of players are on windows and it would be a waste of time. If you would like to make a linux build and fix the bugs, go ahead!

But for the hxCodec on linux problem you mentioned there's a special installing process for it: [https://github.com/polybiusproxy/hxCodec#linux](url)

If you ever make linux work, make a Pull!

**Comment by REALHaydenGaming** [comment]
> Hello, thanks for the concern, but I never intended on making a linux build. This is for many reasons, but mostly because like 99% of players are on windows and it would be a waste of time. If you would like to make a linux build and fix the bugs, go ahead!
> 
> But for the hxCodec on linux problem you mentioned there's a special installing process for it: [https://github.com/polybiusproxy/hxCodec#linux](url)
> 
> If you ever make linux work, make a Pull!

Thank you! I was gonna make a fixed build fixing all of the current issue's!
For most user's (Like me) to play on! Fully functional piece of work I was planning on.

**Comment by REALHaydenGaming** [comment]
> > Hello, thanks for the concern, but I never intended on making a linux build. This is for many reasons, but mostly because like 99% of players are on windows and it would be a waste of time. If you would like to make a linux build and fix the bugs, go ahead!
> > But for the hxCodec on linux problem you mentioned there's a special installing process for it: [https://github.com/polybiusproxy/hxCodec#linux](url)
> > If you ever make linux work, make a Pull!
> 
> Thank you! I was gonna make a fixed build fixing all of the current issue's! For most user's (Like me) to play on! Fully functional piece of work I was planning on.

Oh wait, it is STILL accruing. This is why I am removing video support from linux
![fuck hx codec, I would want it removed](https://user-images.githubusercontent.com/107285739/190916346-169b9ff0-bffe-4b9a-a027-14fab35dadec.png)

**Comment by REALHaydenGaming** [comment]
> > > Hello, thanks for the concern, but I never intended on making a linux build. This is for many reasons, but mostly because like 99% of players are on windows and it would be a waste of time. If you would like to make a linux build and fix the bugs, go ahead!
> > > But for the hxCodec on linux problem you mentioned there's a special installing process for it: [https://github.com/polybiusproxy/hxCodec#linux](url)
> > > If you ever make linux work, make a Pull!
> > 
> > 
> > Thank you! I was gonna make a fixed build fixing all of the current issue's! For most user's (Like me) to play on! Fully functional piece of work I was planning on.
> 
> Oh wait, it is STILL accruing. This is why I am removing video support from linux ![fuck hx codec, I would want it removed](https://user-images.githubusercontent.com/107285739/190916346-169b9ff0-bffe-4b9a-a027-14fab35dadec.png)

Wait a damn second, I could just edit the project.xml and remove support for linux using the:

unless="whateverthehellplatformitis"

**Comment by REALHaydenGaming** [comment]
> 
> Wait a damn second, I could just edit the project.xml and remove support for linux using the:
> 
> unless="whateverthehellplatformitis"

oh wait, that break's the entire MP4Handler.hx file.

**Comment by REALHaydenGaming** [comment]
Actually, I'll just remove cutscene support entirely, and I'll let people uncomment the shit so they can re-add it back.

**Comment by REALHaydenGaming** [comment]
Then I can make a pr with a media fire link (no more dev's folder as well lol! that is useless af!)

**Comment by REALHaydenGaming** [comment]
alright, praying ong if this shit work's.
![Screenshot 2022-09-18 12 59 47 PM](https://user-images.githubusercontent.com/107285739/190919218-4014932d-77bc-4b07-acec-99d8f4d77cb4.png)

**Comment by REALHaydenGaming** [comment]
Alright lunar, you may close this now.
Just lemme test some stuff before I send you the media fire so I can let you steal some of my code over.

**Comment by lunarcleint** [comment]
lmao, nice

if it works good make a pull i want to see it

**Comment by REALHaydenGaming** [comment]
> lmao, nice
> 
> if it works good make a pull i want to see it

Here is a list of thing's I MIGHT add:

A worse mickey on the title screen if you have nub mode on (or as I call him, pissy mickey).

Memory can now be under 900 mb's.

More effects to songs. (Mainly that funny 2nd devil haha fuck you go kys mickey good ending song).

Readded the OLD version of the song "Untold Loneliness" (seriously, I suck at spelling LMAO).
Just type in the Debug Menu "UL-Old".

No more pissy openfl fake fps dumb shit.

New FPS font.

**Comment by REALHaydenGaming** [comment]
Just trying to fix a segment dump currently. Relating to the mickeysangre.png (seriously, it's somehow EVEN scarier than EVER before.)
