### ISSUE TITLE
how to make song extension mechanic?

### ISSUE THREAD

**Issue by ghost** [lunarcleint/Wednesdays-Infidelity#14]
### Describe your problem here.

hi, can i have the song extension mechanic like unknown suffering

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHoovy** [comment]
> ### Describe your problem here.
> hi, can i have the song extension mechanic like unknown suffering
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Neko, HashLink, or other build system
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

😐 just look in the source code or song script files for it

**Comment by ghost** [comment]
I did not find it either in the source code or in lua

**Comment by MemeHoovy** [comment]
> I did not find it either in the source code or in lua

there is no lua, it might be in the song scripts, they're hx files in the songs folders in the preload data folder

**Comment by ghost** [comment]
hx doesn't have it

**Comment by MemeHoovy** [comment]
> hx doesn't have it

🙄
https://github.com/lunarcleint/Wednesdays-Infidelity/blob/master/assets/preload/data/unknown-suffering/script.hx

**Comment by lunarcleint** [comment]
Just setting the `songLength` to the time you want and it will modify the time bar to make the song look shorter then it is (its in milliseconds btw). Then when you want to set it back change it to `FlxG.sound.music.length`

**Comment by ghost** [comment]
no working
