### ISSUE TITLE
will the chromatics or MIDIS ever get released?

### ISSUE THREAD

**Issue by MemeHoovy** [lunarcleint/Wednesdays-Infidelity#15]
### What is your question?

I know you ain't gonna give out FLPS, **I can just tell**, so I'm wondering if the chromatics or midi's will get released. (the chromatics I need for a cover btw)

**Comment by lunarcleint** [comment]
Chromatics: [https://drive.google.com/drive/folders/1jJRyj6Nlcb_eMAQ9yEqQqGyLFeVc4nZj](https://drive.google.com/drive/folders/1jJRyj6Nlcb_eMAQ9yEqQqGyLFeVc4nZj)

Flps will depend on musician

**Comment by MemeHoovy** [comment]
okay, thanks
