### ISSUE TITLE
What editing DID you guys do to make the vocal effects for Unknown Suffering Mouse anyway?

### ISSUE THREAD

**Issue by ChandelureF-5** [lunarcleint/Wednesdays-Infidelity#17]
### What is your question?

I only ask this so that people have the option to make their already existing chromatics more WI like. I also ask that you please only answer if your comfortable doing so.

**Comment by MemeHoovy** [comment]
chromatics: https://drive.google.com/drive/folders/1jJRyj6Nlcb_eMAQ9yEqQqGyLFeVc4nZj
as for the effect, idk, ask one of the musicians who did the chroms

**Comment by lunarcleint** [comment]
Ask GoddessAwe, she made the voices
