### ISSUE TITLE
Also, I request a small modification to the main menu background.

### ISSUE THREAD

**Issue by ChandelureF-5** [lunarcleint/Wednesdays-Infidelity#18]
### What feature do you want to get added on the **base** engine?

You should add a note next to the needle on the main menu that says "If you want it done do it yourself. Stop pestering lunarcleint and just let him work on the engine." and have it signed by Mickey. Or I could try doing it if ya want. No biggie.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ChandelureF-5** [comment]
By the way, yes, I'm jabbing at the people requesting the stage editor, extra keys support and winning icons.

**Comment by ChandelureF-5** [comment]
Those guys need to just leave you alone and do it themselves for once.

**Comment by lunarcleint** [comment]
No one request them

**Comment by ChandelureF-5** [comment]
~.~
