### ISSUE TITLE
how to fix this???

### ISSUE THREAD

**Issue by I-am-someone-sh** [lunarcleint/Wednesdays-Infidelity#24]
### Describe your problem here.

source/vlc/MP4Handler.hx:5: characters 8-28 : Type not found : vlc.bitmap.VlcBitmap
source/vlc/MP4Handler.hx:11: characters 26-35 : Type not found : VlcBitmap

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Fearester2008** [comment]
lunarcleint help me with HUD switcher

**Comment by Fearester2008** [comment]
Please

**Comment by davidfnf** [comment]
help as well

**Comment by moxie-coder** [comment]
use hxCodec 2.5.1

**Comment by davidfnf** [comment]
didnt work

**Comment by moxie-coder** [comment]
> didnt work

haxelib install hxCodec 2.5.1

**Comment by davidfnf** [comment]
thx it worked

**Comment by moxie-coder** [comment]
np
