### ISSUE TITLE
HOW DO I SOLVE THIS PROBLEM?! PLEASE, HELP!

### ISSUE THREAD

**Issue by MaksPRO12667** [lunarcleint/Wednesdays-Infidelity#27]
### Describe your problem here.

source/data/SpecsDetector.hx:39: characters 14-25 : Cannot compare cpp.UInt64 and Int
source/util/Paths.hx:4: characters 8-25 : You cannot access the flash package while in a macro (for flash.media.Sound)
C:\Users\MaksonKolivan\Desktop\asshackin\Wednesdays-Infidelity-master\Wednesdays-Infidelity-master\source\import.hx:1: characters 8-18 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,1/src/lime/app/Application.hx:654: characters 53-100 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,1/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,1/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,1/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,1/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,1/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,1/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,1/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,1/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,1/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

PLEASE HELP, I'VE BEEN SUFFERING WITH THIS COMPILATION FOR A YEAR ALREADY! (lol "suffering" sounds funny)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
you’re supposed to use haxe 4.2.5

**Comment by MaksPRO12667** [comment]
> you’re supposed to use haxe 4.2.5

Ok.. I try it

**Comment by MaksPRO12667** [comment]
> you’re supposed to use haxe 4.2.5

C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field

One error

**Comment by moxie-coder** [comment]
> > you’re supposed to use haxe 4.2.5
> 
> C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field
> 
> One error

use flixel addons 3.0.2 and flixel 5.2.2

**Comment by MaksPRO12667** [comment]
> use flixel addons 3.0.2 and flixel 5.2.2

C:/HaxeToolkit/haxe/lib/flixel/5,2,2/flixel/system/FlxSound.hx:752: characters 17-25 : flash.media.SoundChannel has no field __source
C:/HaxeToolkit/haxe/lib/flixel/5,2,2/flixel/system/FlxSound.hx:753: characters 14-22 : flash.media.SoundChannel has no field __source
source/Main.hx:129: characters 53-57 : Float should be Int
source/Main.hx:129: characters 53-57 : ... For optional function argument 'updateFramerate'
source/Main.hx:129: characters 53-57 : ... For function argument 'child'

**Comment by 2JENO** [comment]
> > use flixel addons 3.0.2 and flixel 5.2.2
> 
> C:/HaxeToolkit/haxe/lib/flixel/5,2,2/flixel/system/FlxSound.hx:752: characters 17-25 : flash.media.SoundChannel has no field __source
> C:/HaxeToolkit/haxe/lib/flixel/5,2,2/flixel/system/FlxSound.hx:753: characters 14-22 : flash.media.SoundChannel has no field __source
> source/Main.hx:129: characters 53-57 : Float should be Int
> source/Main.hx:129: characters 53-57 : ... For optional function argument 'updateFramerate'
> source/Main.hx:129: characters 53-57 : ... For function argument 'child'

use flixel 4.11.0

**Comment by MaksPRO12667** [comment]
> use flixel 4.11.0

THANK YOU! It helped me! I thank everyone who helped me with this... FINALLY A YEAR OF TORMENT IS OVER! THANKS A LOT!

**Comment by 2JENO** [comment]
> > use flixel 4.11.0
> 
> THANK YOU! It helped me! I thank everyone who helped me with this... FINALLY A YEAR OF TORMENT IS OVER! THANKS A LOT!

no problem

**Comment by MaksPRO12667** [comment]
> no problem

Cool, but i have new problem after compilation:
When click on the mouse button, the game starts to crash with the error "Invalid field:clickCount" I don't know how to fix it, and the song "Leak Ma Balls" also does not start and the game crashes. Help solve problems

I dunno how fix it

**Comment by 2JENO** [comment]
> > no problem
> 
> Cool, but i have new problem after compilation:
> When click on the mouse button, the game starts to crash with the error "Invalid field:clickCount" I don't know how to fix it, and the song "Leak Ma Balls" also does not start and the game crashes. Help solve problems
> 
> I dunno how fix it

maybe you should use flixel-addons 2.11.0

**Comment by 2JENO** [comment]
> I dunno how fix it

`haxelib set lime 8.0.0`
`haxelib set openfl 9.2.2`
`haxelib set flixel 4.11.0`
`haxelib set flixel-addons 2.11.0`
`haxelib set flixel-ui 2.5.0`
`haxelib set hscript 2.5.0`
`haxelib set flixel-tools 1.5.1`

set lib this

**Comment by MaksPRO12667** [comment]
> `haxelib set lime 8.0.0` `haxelib set openfl 9.2.2` `haxelib set flixel 4.11.0` `haxelib set flixel-addons 2.11.0` `haxelib set flixel-ui 2.5.0` `haxelib set hscript 2.5.0` `haxelib set flixel-tools 1.5.1`
> 
> set lib this

"Invalid field:clickCount" error is destroyed, but the song "Leak Ma Balls" also crashes
Credits crashes too

**Comment by MaksPRO12667** [comment]
The game crashes because:
1) Credits
Error: source/util/Paths.hx:310: oh no its returning null NOOOO assets/images/credits/Jhaix.png,null
2) Song: Leak Ma Balls
Errors: source/song/Conductor.hx:78: new BPM map BUDDY []
source/util/Paths.hx:310: oh no its returning null NOOOO assets/images/backgrounds/leakers/oswald.png,shared

**Comment by 2JENO** [comment]
that error is happen if file is not found
