### ISSUE TITLE
HI LUNAR

### ISSUE THREAD

**Issue by obamacat3** [lunarcleint/Wednesdays-Infidelity#3]
### What is your question?

hey lunar if your reading this im gonna tell u something (on github bc idk where to find u elsewhere lol)

hey lunar you teached me the basics of fnf coding im so gratefull for that <3
i originally found you on a youtube video 7-9 months ago in the comment section of a guy nammed catbro brothers or whatever his name was
you said that you had a better tutorial and indeed! you did!
i find it shocking that i find u again RANDOMLY while you are on the credits on a mod as big as WI

well thats it just a crazy story bye and thanks for everything bro <33333

**Comment by lunarcleint** [comment]
omg your so cool lmao, <33

**Comment by lunarcleint** [comment]
made my day :))

**Comment by Reycko** [comment]
wholesome-est moment ever

**Comment by MemeHoovy** [comment]
that's so wholesome :)
