### ISSUE TITLE
Okay, I really have no idea what I'm doing...

### ISSUE THREAD

**Issue by EnderShadowborne** [lunarcleint/Wednesdays-Infidelity#30]
### Describe your problem here.

Since the main FNF github doesn't have a "Help Wanted" label, I'll just post here, since it's about the same anyway...

I've tried following the directions on the main FNF github building instructions TO THE LETTER, and lime test windows doesn't boot the game up, it just throws errors at me, I already went ahead and deleted the folder containing the otherwise source code from FNF, AND closed my command prompt... I'm not really sure what to do, except maybe ask for a video showing how to do this correctly, or maybe request contact outside of here (like Discord), and be walked through it step by step (Given that's how I learn anyway; hands-on training with human feedback and what have you... Autism walking, I know...)

If that's not feasible, then could I just get the private build? Would love to be able to see botplay on Untold Loneliness anyhow, that's all I really wanted to achieve; getting to do botplay on UL.

Thanks

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by moxie-coder** [comment]
can you show the errors you’ve been having?

**Comment by EnderShadowborne** [comment]
I'll have to re-attempt the entire build, that okay?

**Comment by moxie-coder** [comment]
> I'll have to re-attempt the entire build, that okay?

yeah just as long as I can see the problem

**Comment by moxie-coder** [comment]
you should know psych and the base game are not the same thing, source wise and in general

**Comment by EnderShadowborne** [comment]
> you should know psych and the base game are not the same thing, source wise

I had no idea, sorry about that...

**Comment by EnderShadowborne** [comment]
> > I'll have to re-attempt the entire build, that okay?
> 
> yeah just as long as I can see the problem

Alright, gimme a few...

**Comment by EnderShadowborne** [comment]
I suppose the first thing I should be asking right now, before I go any further, should the source code for WI be in the folder called "funkin" PRIOR TO running the git clone command? Or after?

**Comment by EnderShadowborne** [comment]
Alright, so... when I do lime test windows, I get the following:

` source/Prebuild.hx:15: Building...
source/funkin/util/macro/GitCommit.hx:26: Git Commit ID: 9b483de
source/funkin/util/macro/GitCommit.hx:101: Git Status Output:
source/funkin/util/macro/GitCommit.hx:55: Git Branch Name: main
source/funkin/ui/credits/CreditsDataMacro.hx:13: Hardcoding credits data...
source/funkin/ui/credits/CreditsDataHandler.hx:39: CreditsData(33 entries containing 113 lines)
 WARNING  F:/fnf building shit/funkin/.haxelib/thx,core/git/src/thx/Weekday.hx:7: characters 1-7

   7 | @:enum
     | ^^^^^^
     | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  F:/fnf building shit/funkin/.haxelib/thx,core/git/src/thx/Weekday.hx:7: characters 1-7

   7 | @:enum
     | ^^^^^^
     | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  source/funkin/play/ResultState.hx:875: lines 875-887

 875 |                 FlxG.switchState(FreeplayState.build(
   - |                   [...]
 887 |                   }));
     |
     | (WDeprecated) use `MyState.new` or `()->new MyState()` instead of `new MyState()`)

 WARNING  source/funkin/play/components/HealthIcon.hx:208: characters 38-55

 208 |         var targetSize:Int = Std.int(MathUtil.coolLerp(this.width, HEALTH_ICON_SIZE * this.size.x, 0.15));
     |                                      ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/play/components/HealthIcon.hx:214: characters 38-55

 214 |         var targetSize:Int = Std.int(MathUtil.coolLerp(this.height, HEALTH_ICON_SIZE * this.size.y, 0.15));
     |                                      ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/play/components/HealthIcon.hx:220: characters 20-37

 220 |       this.angle = MathUtil.coolLerp(this.angle, 0, 0.15);
     |                    ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/Alphabet.hx:224: characters 11-28

 224 |       y = MathUtil.coolLerp(y, (scaledY * 120) + (FlxG.height * 0.48), 0.16);
     |           ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/Alphabet.hx:225: characters 11-28

 225 |       x = MathUtil.coolLerp(x, (targetY * 20) + 90, 0.16);
     |           ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/MenuItem.hx:48: characters 9-26

  48 |     y = MathUtil.coolLerp(y, (targetY * 120) + 480, 0.17);
     |         ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/freeplay/SongMenuItem.hx:703: characters 11-28

 703 |       x = MathUtil.coolLerp(x, targetPos.x, 0.3);
     |           ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/freeplay/SongMenuItem.hx:704: characters 11-28

 704 |       y = MathUtil.coolLerp(y, targetPos.y, 0.4);
     |           ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/options/FunkinSoundTray.hx:80: characters 9-26

  80 |     y = MathUtil.coolLerp(y, lerpYPos, 0.1);
     |         ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/options/FunkinSoundTray.hx:81: characters 13-30

  81 |     alpha = MathUtil.coolLerp(alpha, alphaTarget, 0.25);
     |             ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/story/LevelTitle.hx:57: characters 14-31

  57 |     this.y = MathUtil.coolLerp(y, targetY, 0.17);
     |              ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

Error: Could not find include file "F:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/project/Build.xml" `

The error HERE is because I don't have hxCodec installed, and I assume the warnings I can safely ignore... BUT, when I *DO* install hxCodec, and set it to 2.5.1, I get the following:

` source/Prebuild.hx:15: Building...
 ERROR  source/funkin/play/cutscene/VideoCutscene.hx:14: characters 8-37

 14 | import hxcodec.flixel.FlxVideoSprite;
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | Type not found : hxcodec.flixel.FlxVideoSprite `
    
Which is where I just gave up...

EDIT: Just found out that text formatting on here no longer works for me, lovely

**Comment by EnderShadowborne** [comment]
I'm going to guess that judging based on the lack of responses that I'm a bigger noob than anticipated... my bad...

**Comment by moxie-coder** [comment]
> I suppose the first thing I should be asking right now, before I go any further, should the source code for WI be in the folder called "funkin" PRIOR TO running the git clone command? Or after?

nope because that ain’t even the right repo

**Comment by EnderShadowborne** [comment]
> > I suppose the first thing I should be asking right now, before I go any further, should the source code for WI be in the folder called "funkin" PRIOR TO running the git clone command? Or after?
> 
> nope because that ain’t even the right repo

It’s not? Huh… I had no idea… but I’d love to get this to work though…

**Comment by moxie-coder** [comment]
you're supposed to `git clone https://github.com/lunarcleint/Wednesdays-Infidelity` not `https://github.com/FunkinCrew/Funkin`

**Comment by EnderShadowborne** [comment]
*facepaws* Yeah, that’d probably help, I’ll update when I get around to trying this again

EDIT: can anyone tell how much of a noob I am yet? lol

**Comment by EnderShadowborne** [comment]
Okay, so I just got around to doing the thing, but now I'm stuck again; hmm.json isn't in the wednesdays-infidelity directory, and lime isn't installed in the directory either, I suppose it would help if I mention that when I ran `git submodule update --init --recursive`, it returned nothing in the command prompt... what should I do from here?

**Comment by EnderShadowborne** [comment]
Soooo... Shall I mark this closed with the tag "wontfix"?

**Comment by moxie-coder** [comment]
> Okay, so I just got around to doing the thing, but now I'm stuck again; hmm.json isn't in the wednesdays-infidelity directory, and lime isn't installed in the directory either, I suppose it would help if I mention that when I ran `git submodule update --init --recursive`, it returned nothing in the command prompt... what should I do from here?

this doesn't use submodules

**Comment by moxie-coder** [comment]
> Soooo... Shall I mark this closed with the tag "wontfix"?

you can't add tags on issues after creating one, only people who own or are collaborators on the repo can

**Comment by EnderShadowborne** [comment]
> this doesn't use submodules

Okay? So what're my next steps from here? I really have no idea on how to proceed from here, I have no way of building the game, nor can I run Lime or anything like that, hmm is non-existent in the directory, what do I do from here?


> you can't add tags on issues after creating one, only people who own or are collaborators on the repo can

I see.

**Comment by moxie-coder** [comment]
> > this doesn't use submodules
> 
> Okay? So what're my next steps from here? I really have no idea on how to proceed from here, I have no way of building the game, nor can I run Lime or anything like that, hmm is non-existent in the directory, what do I do from here?
> 
> > you can't add tags on issues after creating one, only people who own or are collaborators on the repo can
> 
> I see.

this doesn't use hmm either, you can just download it as a zip then if you're having problems with git, since you don't necessarily need it from this repo tbh, unless it's from your fork

**Comment by EnderShadowborne** [comment]
> this doesn't use hmm either, you can just download it as a zip then if you're having problems with git, since you don't necessarily need it from this repo tbh, unless it's from your fork

Alright, good. but how about when it comes down to when I want to actually build the game? Y'know, since I need to do so THIS way so I can do botplay on UL, how would I go about this?

**Comment by moxie-coder** [comment]
> > this doesn't use hmm either, you can just download it as a zip then if you're having problems with git, since you don't necessarily need it from this repo tbh, unless it's from your fork
> 
> Alright, good. but how about when it comes down to when I want to actually build the game? Y'know, since I need to do so THIS way so I can do botplay on UL, how would I go about this?

download the required libraries, then run `lime build windows`

**Comment by EnderShadowborne** [comment]
> > > this doesn't use hmm either, you can just download it as a zip then if you're having problems with git, since you don't necessarily need it from this repo tbh, unless it's from your fork
> > 
> > 
> > Alright, good. but how about when it comes down to when I want to actually build the game? Y'know, since I need to do so THIS way so I can do botplay on UL, how would I go about this?
> 
> download the required libraries, then run `lime build windows`

Lime isn't installed in the directory, and it WON'T install for whatever reason...

**Comment by moxie-coder** [comment]
> > > > this doesn't use hmm either, you can just download it as a zip then if you're having problems with git, since you don't necessarily need it from this repo tbh, unless it's from your fork
> > > 
> > > 
> > > Alright, good. but how about when it comes down to when I want to actually build the game? Y'know, since I need to do so THIS way so I can do botplay on UL, how would I go about this?
> > 
> > 
> > download the required libraries, then run `lime build windows`
> 
> Lime isn't installed in the directory, and it WON'T install for whatever reason...

you have to do `haxelib run lime setup` then restart

**Comment by EnderShadowborne** [comment]
![image](https://github.com/user-attachments/assets/3ccff964-b2df-4b88-b1d8-bf1ba7023469)

**Comment by moxie-coder** [comment]
> ![image](https://private-user-images.githubusercontent.com/57685260/362438662-3ccff964-b2df-4b88-b1d8-bf1ba7023469.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzYzOTQsIm5iZiI6MTcyNDg3NjA5NCwicGF0aCI6Ii81NzY4NTI2MC8zNjI0Mzg2NjItM2NjZmY5NjQtYjJkZi00Yjg4LWIxZDgtYmYxYmE3MDIzNDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDIwMTQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NWFmOGZlZmQxZWQwZWYwMWY2MzM2YWM2NDEwMmU5NDg5YjllZjBmNzU0MzJjZjdiN2QxM2VmYmFhNTRkOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SREUvvbgHuCb6jQrybxBWFdfFyirB0d1UM3vRAw9TdU)

`haxelib install lime`

**Comment by EnderShadowborne** [comment]
![image](https://github.com/user-attachments/assets/bf9ebe09-2898-4503-bbbb-af9437b40471)

Now we're cooking with bacon grease, and now I believe is the "restart" bit, which means I have to restart my computer?

**Comment by moxie-coder** [comment]
> ![image](https://private-user-images.githubusercontent.com/57685260/362439506-bf9ebe09-2898-4503-bbbb-af9437b40471.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzY2MDYsIm5iZiI6MTcyNDg3NjMwNiwicGF0aCI6Ii81NzY4NTI2MC8zNjI0Mzk1MDYtYmY5ZWJlMDktMjg5OC00NTAzLWJiYmItYWY5NDM3YjQwNDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDIwMTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNzRiNmZjOTRjNzc4NDY3ZDkzMjI3YmFhMDlkMGUxYWNkMDFiNGE0OGRlYWJiZmMwMmMwYjBkMTE4YTI5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5mZH0S_wvf8hIhC2ovhjdgOBTyAtFM9mMvL89QUxGbA)
> 
> Now we're cooking with bacon grease, and now I believe is the "restart" bit, which means I have to restart my computer?

after you run that one command again

**Comment by EnderShadowborne** [comment]
Which command again? `haxelib run lime setup`? Or the build command? Because I already ran the setup command

**Comment by EnderShadowborne** [comment]
![image](https://github.com/user-attachments/assets/8cba3d11-c881-4dcf-a444-e66661eedd6d)
I assume this needs to be installed?

The default FNF compilation guide is pretty garbage at accounting for these, and just to let you know, I ran the config.bat from the WI repo that the `git` command grabbed

**Comment by EnderShadowborne** [comment]
![image](https://github.com/user-attachments/assets/0588480e-0a4e-403f-93df-67060989b8d6)
Lovely, one rabbit hole after another, and I get this.

I'm gonna go out to lunch...

**Comment by moxie-coder** [comment]
> ![image](https://private-user-images.githubusercontent.com/57685260/362445397-0588480e-0a4e-403f-93df-67060989b8d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Nzg1MTIsIm5iZiI6MTcyNDg3ODIxMiwicGF0aCI6Ii81NzY4NTI2MC8zNjI0NDUzOTctMDU4ODQ4MGUtMGE0ZS00MDNmLTkzZGYtNjcwNjA5ODliOGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDIwNTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMTViYWZmZTFjNTI3NzcwYWJhZWIyMWEwYzk5YzI5ZmQ1MmY5NzJiZGZjYWVkNzgyNTI2NTA2OTVkM2M1MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFMR1k7NEk-5QRHyO7zexs3yIVUJeaVgKVg20fLybk0) Lovely, one rabbit hole after another, and I get this.
> 
> I'm gonna go out to lunch...

downgrade to flixel 4.11.0, flixel-addons to 2.11.0 and downgrade lime to 8.0.2

**Comment by EnderShadowborne** [comment]
Command to do so? Is it `haxelib set <libname> <version>`?

**Comment by moxie-coder** [comment]
> Command to do so? Is it `haxelib set <libname> <version>`?

yeah

**Comment by EnderShadowborne** [comment]
![image](https://github.com/user-attachments/assets/872406a5-f8d1-49b3-8485-33c019c11565)

I must apologize for being rather difficult to deal with, Autism walking and all that... I don't like it when things aren't already covered in guides, and I also prefer to be walked through things step-by-step... but meh...

**Comment by EnderShadowborne** [comment]
Wait... do I need to re-setup lime after changing its version?

EDIT: Guess the answer is "no", but still needing to know what to do here

**Comment by moxie-coder** [comment]
> ![image](https://private-user-images.githubusercontent.com/57685260/362463123-872406a5-f8d1-49b3-8485-33c019c11565.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTcyOTgsIm5iZiI6MTcyNDkxNjk5OCwicGF0aCI6Ii81NzY4NTI2MC8zNjI0NjMxMjMtODcyNDA2YTUtZjhkMS00OWIzLTg0ODUtMzNjMDE5YzExNTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA3MzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjOTEzZWEyMDFlZTk1Nzc2NDk4NzVhY2QzZWY0NjQ0ZmEzYjRlM2I2NDdhMTc5MzZjYTQyZDRjMTYzOGE0MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nBYem_KU_OJaTI-pqC5A5EBiZCbQYnMb7wE5J0Z90RE)
> 
> I must apologize for being rather difficult to deal with, Autism walking and all that... I don't like it when things aren't already covered in guides, and I also prefer to be walked through things step-by-step... but meh...

did you make sure flixel is 4.11.0? do `haxelib list` just to make sure

**Comment by EnderShadowborne** [comment]
![image](https://github.com/user-attachments/assets/a7a3477e-ce15-4f85-bb67-fe940f5cb788)
Seems to check out

**Comment by moxie-coder** [comment]
> ![image](https://private-user-images.githubusercontent.com/57685260/362818474-a7a3477e-ce15-4f85-bb67-fe940f5cb788.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NzMwMzYsIm5iZiI6MTcyNDk3MjczNiwicGF0aCI6Ii81NzY4NTI2MC8zNjI4MTg0NzQtYTdhMzQ3N2UtY2UxNS00Zjg1LWJiNjctZmU5NDBmNWNiNzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDIzMDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OTY2NTRmNWZiNTJkYTMzZDY0MjhjYzhkNWFiNjcxYTQ1NTQ3MGNkOTBiYjkyZTlmNjgyYjdlNWU3M2JkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gm6EZ2NareWeg_YeDwPlQ2O-x5gdbtGB1nJKDz-ApZc) Seems to check out

try using Lime 7.9.0, then try building again when you set it as that

**Comment by EnderShadowborne** [comment]
![image](https://github.com/user-attachments/assets/80889a01-d431-4bde-82c3-436ab9848a5f)
This is what I get...

**Comment by EnderShadowborne** [comment]
Is it safe to say I’m on the home stretch? Like the last bit of tinkering before it finally works?

**Comment by moxie-coder** [comment]
> ![image](https://private-user-images.githubusercontent.com/57685260/363050920-80889a01-d431-4bde-82c3-436ab9848a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNjg1ODYsIm5iZiI6MTcyNTA2ODI4NiwicGF0aCI6Ii81NzY4NTI2MC8zNjMwNTA5MjAtODA4ODlhMDEtZDQzMS00YmRlLTgyYzMtNDM2YWI5ODQ4YTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDAxMzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZGY5YTY1OGNmNjlhMTU4MmUzZTNhMmUwNGIwMTFhMTkzNDQ1MjFlZGQ3ZjE4YzE2Y2I3YmJjYzRjYzFjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F9zmt0F6RHbRxtoembYvEVRrRiIvA5qNr_0VY3XvZ8c) This is what I get...

it does not use that at all, this mod was *way* before fnf 0.3

**Comment by EnderShadowborne** [comment]
Use what? Lime? Then what do I do?

**Comment by moxie-coder** [comment]
> Use what? Lime? Then what do I do?

I mean, what version of haxe are you using?

**Comment by EnderShadowborne** [comment]
Oh goodness, I have no clue, I’d have to be at my computer to look, I’m at work atm

The latest one, I guess

**Comment by moxie-coder** [comment]
> Oh goodness, I have no clue, I’d have to be at my computer to look, I’m at work atm
> 
> The latest one, I guess

you can do `haxe --version` when you get back, but if you are, make sure to downgrade to 4.2.5 since this wasn't made for the latest version at all

**Comment by EnderShadowborne** [comment]
I’m guessing the command to downgrade is `haxe set 4.2.5`? Or do I have to go on the site?

**Comment by moxie-coder** [comment]
> I’m guessing the command to downgrade is `haxe set 4.2.5`? Or do I have to go on the site?

you have to download it from the website

**Comment by EnderShadowborne** [comment]
Understood, more updates later down the line

**Comment by EnderShadowborne** [comment]
```
F:\fnf building shit\Wednesdays-Infidelity>lime test windows

Compiling group: haxe
cl.exe -Iinclude -IF:/HaxeToolkit/haxe/lib/discord_rpc/1,0,0/linc/ -I F:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/lib/vlc/include/ -I F:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/lib/vlc/src/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdF:\fnf building shit\Wednesdays-Infidelity\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IF:/HaxeToolkit/haxe/lib/hxcpp/4,3,2/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/flixel/util/FlxPool_flixel_effects_FlxFlicker.cpp
 - src/flixel/tweens/motion/LinearPath.cpp
 - src/states/substates/MusicBeatSubstate.cpp
 - src/openfl/display/DOMRenderer.cpp  [haxe,release]
 - src/lime/system/_ThreadPool/ThreadPoolMessage.cpp
 - src/lime/_internal/backend/native/TextEventInfo.cpp
 - src/flixel/input/actions/_FlxSteamController/FlxSteamUpdater.cpp
 - src/openfl/display/_internal/Context3DElementType.cpp
 - src/openfl/system/SecurityDomain.cpp  [haxe,release]
 - src/flixel/input/actions/_FlxSteamController/FlxSteamControllerMetadata.cpp
 - src/sys/io/_Process/Stdout.cpp
 - src/gameObjects/MenuCharacter.cpp
 - src/flixel/system/debug/interaction/tools/Pointer.cpp
 - src/lime/media/openal/ALC.cpp  [haxe,release]
 - src/flxanimate/data/_AnimationData/Layers_Impl_.cpp
 - src/sys/io/FileOutput.cpp
 - src/openfl/display/_GradientType/GradientType_Impl_.cpp
 - src/__ASSET__flixel_fonts_nokiafc22_ttf.cpp
 - src/lime/text/harfbuzz/HBGlyphPosition.cpp
 - src/openfl/text/_internal/ShapeCache.cpp  [haxe,release]
 - src/flxanimate/FilterShader.cpp
 - src/flixel/util/_FlxUnicodeUtil/UnicodeBuffer_Impl_.cpp
 - src/openfl/display/Stage3D.cpp  [haxe,release]
 - src/input/PlayerSettings.cpp
 - src/haxe/crypto/BaseCode.cpp
 - src/flixel/input/gamepad/mappings/PSVitaMapping.cpp
 - src/flixel/FlxState.cpp
 - src/lime/graphics/opengl/ext/OES_surfaceless_context.cpp
 - src/__ASSET__assets_fonts_waltographui_ttf.cpp
 - src/lime/system/_Locale/Locale_Impl_.cpp
 - src/flixel/input/gamepad/FlxAnalogToDigitalMode.cpp
 - src/lime/graphics/cairo/_CairoFontFace/CairoFontFace_Impl_.cpp
 - src/flixel/system/debug/GraphicInteractive.cpp
 - src/openfl/display/Tileset.cpp  [haxe,release]
 - src/lime/app/_Event_lime_graphics_RenderContext_Void.cpp  [haxe,release]
 - src/flixel/system/debug/watch/TrackerProfile.cpp
 - src/__boot__.cpp
 - src/data/ClientPrefs.cpp
 - src/sys/thread/_Thread/HaxeThread.cpp
 - src/openfl/display/ShaderParameter_Float.cpp
 - src/lime/net/curl/CURLMultiMessage.cpp
 - src/flixel/addons/ui/interfaces/IFlxUIState.cpp
 - src/openfl/display/_internal/Context3DDisplayObject.cpp  [haxe,release]
 - src/openfl/display/_internal/CanvasTextField.cpp
 - src/openfl/display/_InterpolationMethod/InterpolationMethod_Impl_.cpp
 - src/lime/graphics/_OpenGLES3RenderContext/OpenGLES3RenderContext_Impl_.cpp
 - src/openfl/net/URLRequestDefaults.cpp  [haxe,release]
 - src/openfl/events/InvokeEvent.cpp  [haxe,release]
 - src/gameObjects/BGSprite.cpp
 - src/__ASSET__OPENFL__assets_fonts_waltographui_ttf.cpp
 - src/lime/media/WebAudioContext.cpp
 - src/lime/graphics/_WebGL2RenderContext/WebGL2RenderContext_Impl_.cpp
 - src/openfl/display/_internal/_DrawCommandReader/OverrideBlendModeView_Impl_.cpp
 - src/openfl/display/_StageAlign/StageAlign_Impl_.cpp
 - src/lime/text/GlyphMetrics.cpp  [haxe,release]
 - src/flixel/input/gamepad/id/SwitchJoyconLeftID.cpp
 - src/flixel/input/actions/FlxActionManager.cpp
 - src/openfl/events/IEventDispatcher.cpp
 - src/lime/media/FlashAudioContext.cpp
 - src/flixel/input/keyboard/FlxKeyboard.cpp
 - src/flixel/addons/ui/ButtonLabelStyle.cpp
 - src/flixel/input/actions/FlxInputDeviceObject.cpp
 - src/__ASSET__assets_fonts_milkynice_ttf.cpp
 - src/openfl/display/ITileContainer.cpp
 - src/flixel/addons/ui/FlxUIText.cpp
 - src/lime/_internal/format/BMP.cpp  [haxe,release]
 - src/haxe/io/Input.cpp
 - src/flixel/IFlxBasic.cpp
 - src/lime/media/openal/AL.cpp  [haxe,release]
 - src/flixel/input/actions/FlxActionInputDigitalGamepad.cpp
 - src/lime/graphics/opengl/ext/OES_texture_half_float_linear.cpp
 - src/discord_rpc/DiscordRpc.cpp
 - src/__ASSET__flixel_flixel_ui_img_hilight_png.cpp
 - src/lime/utils/_Int8Array/Int8Array_Impl_.cpp
 - src/flixel/system/debug/watch/Watch.cpp
 - src/lime/utils/_Assets/LibrarySymbol.cpp  [haxe,release]
 - src/flxanimate/FlxAnimate.cpp
Error: __boot__.cpp
F:/HaxeToolkit/haxe/lib/discord_rpc/1,0,0/linc/linc_discord_rpc.h(7): fatal error C1083: Cannot open include file: '../lib/discord-rpc/include/discord-rpc.h': No such file or directory
```

Well, got this now... So now I think the issue is isolated down to discord_rpc

**Comment by EnderShadowborne** [comment]
Or am I completely wrong? I'm not an expert

**Comment by moxie-coder** [comment]
> Or am I completely wrong? I'm not an expert

`haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`

**Comment by EnderShadowborne** [comment]
Alright, got it now, though an unrelated question; should I be updating haxelib? Or is that not necessary?

**Comment by EnderShadowborne** [comment]
It works, thanks a ton, and sorry again for being difficult to deal with

Although I must mention that the "flash white" isn't quite like what I'm familiar with, is this due to the tag `<define name="PRIVATE_BUILD"/>`?

**Comment by EnderShadowborne** [comment]
Oh, and flash black doesn't seem to work either, am I doing something wrong? Is it the tag?

**Comment by moxie-coder** [comment]
> It works, thanks a ton, and sorry again for being difficult to deal with
> 
> 
> 
> Although I must mention that the "flash white" isn't quite like what I'm familiar with, is this due to the tag `<define name="PRIVATE_BUILD"/>`?

from what I'm seeing, it does have control of certain aspects but it's commented out by default, unless you removed the comment blocks on it?

**Comment by EnderShadowborne** [comment]
I did

**Comment by moxie-coder** [comment]
> I did

then that might be why

**Comment by EnderShadowborne** [comment]
Mmkay, but I do kinda want it so I can be able to do botplay on UL

**Comment by moxie-coder** [comment]
> Mmkay, but I do kinda want it so I can be able to do botplay on UL

alright, it's up to you on what you wanna do there

**Comment by EnderShadowborne** [comment]
I'll try it both ways

**Comment by EnderShadowborne** [comment]
Just tried it without the private build tag, same issue

**Comment by moxie-coder** [comment]
hmm, try `haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp` and if it does prompt you for something when you compile, hit Y

**Comment by EnderShadowborne** [comment]
That did the trick, thank you

**Comment by moxie-coder** [comment]
> That did the trick, thank you

np
