### ISSUE TITLE
Will the .flas get released?

### ISSUE THREAD

**Issue by CheesecakeForever** [lunarcleint/Wednesdays-Infidelity#5]
### What is your question?

The title

**Comment by CheesecakeForever** [comment]
ik, but i need them. i posess the power of adobe animate so i need them now. for anything really

**Comment by CheesecakeForever** [comment]
lol

**Comment by CheesecakeForever** [comment]
ok, or i could wait for the answer of lunarcli- i mean thanks :)

**Comment by lunarcleint** [comment]
Zero’s FLAs (sprites): [here](https://www.mediafire.com/file/4nxodngxpic6h7j/W.I_FLAS.rar/file)
